### PR TITLE
Add instruction for Mixtral 8x22B

### PR DESCRIPTION
**Pull request by RissyRan**
# Description

Add instruction for Mixtral 8x22B on Trillium

### CODE REVIEW

**Review by vipannalla — APPROVED** [review]

**Comment by stingram** [comment]
@RissyRan Is this still WIP or should I review?

**Comment by mailvijayasingh** [comment]
LGTM!

**Comment by RissyRan** [comment]
> @RissyRan Is this still WIP or should I review?

Yes, now it's ready to review. Thanks!

**Review by vipannalla — DISMISSED** [review]
LGTM

**Review by richjames0 — APPROVED** [review]
Looks good! Some nits in case you agree and want to address

1. Could state up top what we're trying to do at a high level - install and execute in parallel on a TPU VM
2. Could mention that v5 is ok since we're all using that now anyway
3. Could move checkpoint conversion to appendix and update surrounding code accordingly
4. Put quantize_kvcache=True on a newline
5. Add --run-eval true, with an indication of what good looks like

**Comment by mailvijayasingh** [comment]
LGTM!

**Review by vipannalla — APPROVED** [review]
LGTM

**Pull request merged**
